name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          cabal-version: '3.4'
          ghc-version: '7.4.1'
      - run: ghc --version
